### ISSUE TITLE
WFS will be uplod to the qgiscloud

### ISSUE THREAD

**Issue by Amphibitus** [qgiscloud/qgis-cloud-plugin#64]
WFS connections are loaded onto the cloud as upload data.

With WFS connections, just like with WMS connections, only the link should be stored in the Qgis project and not the complete data should be uploaded to the qgiscloud.

WFS=Web Feature Services

**Comment by tpo** [comment]
@hdus @mwa ?

**Comment by hdus** [comment]
The WFS are loaded into the database as layers. This is the behavior we want. We originally intended WFS to be treated as such by QGIS Cloud as well. However, it turned out very negatively that there could be significant performance problems of the client. That is why we refrained from further support of this feature.

**Comment by tpo** [comment]
Seeing @hdus answer I guess I close this ticket?
